name: rachman_pos
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  badges: ^0.0.6
  http: ^0.12.0+1
  charts_flutter: ^0.5.0
  shared_preferences: ^0.5.1+1
  scoped_model: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/app/assets/gheaProfile.jpg
    - lib/app/assets/background.png
    - lib/app/assets/fb_icon_325x325.png
    - lib/app/assets/dummyImage.png